apiVersion: v1
entries:
  trident-protect-console:
  - apiVersion: v2
    appVersion: 26.05.0-console
    created: "2026-05-05T23:43:20.705543+05:30"
    dependencies:
    - name: trident-protect
      repository: ""
      version: 100.2605.0-console
    description: helm chart for NetApp Trident Protect Connector and Trident Protect.
    digest: 3fe7d677e56d5762e73310acf2ed0a4c270369635db9a55afeb60c8b6ebb1418
    kubeVersion: '>= 1.24.0-0'
    name: trident-protect-console
    type: application
    urls:
    - https://sachinrai28.github.io/trident-protect-helm-test/charts/trident-protect-console-100.2605.0-console.tgz
    version: 100.2605.0-console
  - apiVersion: v2
    appVersion: 26.04.0-console
    created: "2026-05-05T23:43:20.701773+05:30"
    dependencies:
    - name: trident-protect
      repository: ""
      version: 100.2604.0-console
    description: helm chart for NetApp Trident Protect Connector and Trident Protect.
    digest: 173a0c0e581251ee5121b56a1051cbbed4973b24c719b7bb532d15ecc2b36505
    kubeVersion: '>= 1.24.0-0'
    name: trident-protect-console
    type: application
    urls:
    - https://sachinrai28.github.io/trident-protect-helm-test/charts/trident-protect-console-100.2604.0-console.tgz
    version: 100.2604.0-console
generated: "2026-05-05T23:43:20.695814+05:30"
